version: '3.8'
services:
  pgsql_db:
    image: postgres:${PG_VERSION}
    container_name: ${PG_CONTAINER_NAME}
    hostname: ${PG_HOST}
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - TZ=Asia/Tokyo
    volumes:
      - db_vol:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./log/postgres:/log
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' # PostgreSQLをカスタム設定ファイルで起動
    env_file:
      - .env

  api:
    build: .
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./main.py:/app/main.py
      - ./api:/app/api
      - ./logger.ini:/app/logger.ini
      - ./log/api:/app/log/api
    ports:
      - "8000:8000"
    depends_on:
      - pgsql_db
    env_file:
      - .env

volumes:
  db_vol:
    external: true
